package com.collinpendleton.yana.data.rt

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The awareness codec against bytes the real libraries produced: the
 * fixtures below were generated by y-protocols 1.0.7's
 * encodeAwarenessUpdate over yjs 13.6.32 (the same pair the web client
 * ships), with the client ids pinned, so drift breaks loudly here
 * rather than quietly on a device.
 */
class AwarenessTest {
    @Test
    fun encodesTheReferencePayload() {
        // clientID 4242, clock 2, state: user collin with a cursor whose
        // anchor sits after the emoji and head past the end.
        val stateJson =
            """{"user":{"name":"collin","color":"#c65314","colorLight":"#c6531433"},""" +
                """"cursor":{"anchor":{"type":null,"tname":"body","item":{"client":4242,"clock":3},"assoc":0},""" +
                """"head":{"type":null,"tname":"body","item":null,"assoc":0}}}"""
        val expected =
            "01922102db017b2275736572223a7b226e616d65223a22636f6c6c696e222c22636f6c6f72223a2223" +
                "633635333134222c22636f6c6f724c69676874223a22236336353331343333227d2c22637572736f7222" +
                "3a7b22616e63686f72223a7b2274797065223a6e756c6c2c22746e616d65223a22626f6479222c2269" +
                "74656d223a7b22636c69656e74223a343234322c22636c6f636b223a337d2c226173736f63223a307d" +
                "2c2268656164223a7b2274797065223a6e756c6c2c22746e616d65223a22626f6479222c226974656d" +
                "223a6e756c6c2c226173736f63223a307d7d7d"
        assertArrayEquals(hex(expected), Awareness.encode(4242, 2, stateJson))
    }

    @Test
    fun decodesTheReferencePayload() {
        // y-protocols' bytes for client 9999999, clock 2, user "wren"
        // with a cursor. The varint of 9999999 spans five bytes.
        val payload =
            "01fface20402f1017b2275736572223a7b226e616d65223a227772656e222c22636f6c6f72223a222332" +
                "6337666238222c22636f6c6f724c69676874223a22233263376662383333227d2c22637572736f7222" +
                "3a7b22616e63686f72223a7b2274797065223a6e756c6c2c22746e616d65223a22626f6479222c2269" +
                "74656d223a7b22636c69656e74223a393939393939392c22636c6f636b223a327d2c226173736f6322" +
                "3a307d2c2268656164223a7b2274797065223a6e756c6c2c22746e616d65223a22626f6479222c2269" +
                "74656d223a7b22636c69656e74223a343234322c22636c6f636b223a337d2c226173736f63223a307d" +
                "7d7d"
        val entries = Awareness.decode(hex(payload))
        assertNotNull(entries)
        assertEquals(1, entries!!.size)
        val e = entries[0]
        assertEquals(9999999L, e.clientID)
        assertEquals(2L, e.clock)
        val (user, cursor) = PresenceState.decode(e.stateJson!!)!!
        assertEquals("wren", user.name)
        assertEquals("#2c7fb8", user.color)
        assertEquals("#2c7fb833", user.colorLight)
        assertNotNull(cursor)
        // The cursor positions round-trip as JSON objects.
        val anchorJson = cursor!!.first.decodeToString()
        assertTrue(anchorJson.contains("\"tname\":\"body\""))
        assertTrue(anchorJson.contains("\"client\":9999999"))
    }

    @Test
    fun removalIsTheNullState() {
        // The bytes Awareness.destroy produces: same client, clock one
        // higher, state the literal null.
        val expected = "01922103046e756c6c"
        assertArrayEquals(hex(expected), Awareness.encode(4242, 3, null))
        val entries = Awareness.decode(hex(expected))!!
        assertEquals(1, entries.size)
        assertNull(entries[0].stateJson)
    }

    @Test
    fun malformedPayloadsDecodeToNull() {
        assertNull(Awareness.decode(byteArrayOf()))
        assertNull(Awareness.decode(byteArrayOf(5))) // count beyond the bytes
        assertNull(Awareness.decode(byteArrayOf(1, 0x92.toByte()))) // truncated mid-varint
    }

    @Test
    fun presenceColorsMatchTheWeb() {
        // The palette hash the web client (web/src/sync.ts) applies, for
        // the same person on every device.
        assertEquals("#8a4b6d", presenceFor("collin").color)
        assertEquals("#7a3fa8", presenceFor("otter-17").color)
        assertEquals("#c65314", presenceFor("guest").color)
        assertEquals("#7a3fa8", presenceFor("a").color)
        // An astral name hashes over the first UTF-16 unit of the pair,
        // exactly as charCodeAt(0) does there.
        assertEquals("#c65314", presenceFor("\uD83D\uDE00user").color)
        val u = presenceFor("collin")
        assertEquals(u.color + "33", u.colorLight)
    }

    @Test
    fun stateWithoutCursorDecodes() {
        val state = """{"user":{"name":"x","color":"#2c7fb8","colorLight":"#2c7fb833"},"cursor":null}"""
        val (user, cursor) = PresenceState.decode(state)!!
        assertEquals("x", user.name)
        assertNull(cursor)
        // Round-trip through our own encoder.
        val json = PresenceState.encode(user, null, null)
        assertTrue(json.contains("\"cursor\":null"))
    }

    private fun hex(s: String): ByteArray = ByteArray(s.length / 2) { i ->
        ((Character.digit(s[i * 2], 16) shl 4) + Character.digit(s[i * 2 + 1], 16)).toByte()
    }
}
